package com.sgs.model.view;

import java.sql.Date;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 19 08:06:39 PDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MarkUpRateMsterVORowImpl extends ViewRowImpl {


    public static final int ENTITY_MARKUPRATEMASTER = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        RateId,
        Geography,
        ServiceCategory,
        MarkupRate,
        EffectiveRom,
        EffectiveTill,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        SgsListVO1,
        SgsListVO2;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int RATEID = AttributesEnum.RateId.index();
    public static final int GEOGRAPHY = AttributesEnum.Geography.index();
    public static final int SERVICECATEGORY = AttributesEnum.ServiceCategory.index();
    public static final int MARKUPRATE = AttributesEnum.MarkupRate.index();
    public static final int EFFECTIVEROM = AttributesEnum.EffectiveRom.index();
    public static final int EFFECTIVETILL = AttributesEnum.EffectiveTill.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int SGSLISTVO1 = AttributesEnum.SgsListVO1.index();
    public static final int SGSLISTVO2 = AttributesEnum.SgsListVO2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MarkUpRateMsterVORowImpl() {
    }
}

