package com.sgs.model.view;

import java.sql.Date;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 19 08:06:39 PDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MarkUpRateMsterVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MarkUpRateMsterVOImpl() {
    }
}

