package com.sgs.model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 21 00:31:36 IST 2022
// ---------------------------------------------------------------------
public interface SGSAppModule extends ApplicationModule {
    void executeViewCriteria();
}

